blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/emrikol/phpcs/discussions
    about: Issues are disabled. Please use GitHub Discussions for questions, ideas, and community support.
